version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-ponto-web
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    restart: unless-stopped
